### ISSUE TITLE
Commit Authorship

### ISSUE THREAD

**Issue by GDsouza** [FGMEMBERS/CitationX#3]
I find it weird that we pull in the CitationX from PAF Team, without preserving their git commit history & authorship.
I made a new repo that has all their history, here : [Great-Geek/CitationX-PAFTeam](https://github.com/Great-Geek/CitationX-PAFTeam )

**Comment by FGDATA** [comment]
Ill bring the commits in later too.
thanks for the pointer.

**Comment by legoboyvdlp** [comment]
Did not realize that they had a repository. Apologies.

**Comment by GDsouza** [comment]
@legoboyvdlp Refer https://sourceforge.net/p/pafteam/addons/ci/master/tree/Aircraft/CitationX/ as my copy is out of date.
